
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define LINE_LENGTH 1000

int main(int argc, char **argv) // Main method generated by atom.io
{
	char *input_file;

		if(argc == 3)
		{
			if (strcmp(argv[0], "-i"))
			{
				input_file = argv[2];
				FILE* input = fopen(input_file, "r"); // Input file for read access only.
				char line [LINE_LENGTH];
				int nonEmptyLines = 0;
				int commentedLines = 0;

				int i = 0;
				while(input_file[i] != '\0')
				{
					i++;
				}
				input_file[i-2] = '\0';
				FILE* output = fopen(strcat(input_file, ".o"), "w"); // Output file for write access // generates if it doesn't exist.
				while (fgets(line, LINE_LENGTH, input) != NULL) // To iterate over the whole file
				{
					if((line[0] == '#'
					&& line[1] == 'i')
					|| (line[))
					{
						char[LINE_LENGTH] includeFile;
						 
					}
					if(!((line[0] == '\t')
						|| (line[0] == '\n')
						|| (line[0] == ' ')
					  || (line[0] == NULL))) // If the line isn't completely empty, tabbed or nulled
						{
							nonEmptyLines++; // Add one to a counter
						}

						for(int i = 0; i < strlen(line); i++) // Iterate over the line by character
						{
							if((line[i] == '/') && (line[i + 1] == '/')) // If the line is a comment
							{
								commentedLines++; // Add one to a counter
								line[i] = '\0';
							}
						}
						fputs(line, output);
					}
					fclose(input);
					fclose(output);
					printf("The total number of lines without comments: %d\n", nonEmptyLines);
					printf("The total number of line with comments (inline & standard): %d\n", commentedLines);
			}
		} else if(argc == 4)
		{
			if(strcmp(argv[2], "-c"))
			{
				input_file = argv[2];
				FILE* input = fopen(input_file, "r"); // Input file for read access only.
				char line [LINE_LENGTH];
				int nonEmptyLines = 0;
				int commentedLines = 0;

				int i = 0;
				while(input_file[i] != '\0')
				{
					i++;
				}
				input_file[i-2] = '\0';

				FILE* output = fopen(strcat(input_file, ".o"), "w"); // Output file for write access // generates if it doesn't exist.
				while (fgets(line, LINE_LENGTH, input) != NULL) // To iterate over the whole file
				{
					if(!((line[0] == '\t')
						|| (line[0] == '\n')
						|| (line[0] == ' ')
					  || (line[0] == NULL))) // If the line isn't completely empty, tabbed, spaced or nulled
						{
							nonEmptyLines++; // Add one to a counter
						}

						for(int i = 0; i < strlen(line); i++) // Iterate over the line by character
						{
							if((line[i] == '/') && (line[i + 1] == '/')) // If the line is a comment
							{
								commentedLines++; // Add one to a counter
							}
						}
						fputs(line, output);
					}
					fclose(input);
					fclose(output);
			}
		}
		return 0;
	}
	
