#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define LINE_LENGTH 1000

int main(int argc, char const *argv[]) // Main method generated by atom.io
{
	// Variable & pointer declaration
	FILE* input = fopen("math_functions.c", "r"); // Input file for read access only.
	char line [LINE_LENGTH];
	int nonEmptyLines = 0;
	int commentedLines = 0;

  FILE* output = fopen("math_functions1.o", "w"); // Output file for write access // generates if it doesn't exist.
	while (fgets(line, LINE_LENGTH, input) != NULL) // To iterate over the whole file
	{
		if(!((line[0] == NULL)
			|| (line[0] == '\t')
			|| (line[0] == '\n')
      || (line[0] == '\0'))) // If the line isn't completely empty, tabbed or nulled
			{
				nonEmptyLines++; // Add one to a counter
			}

			for(int i = 0; i < strlen(line); i++) // Iterate over the line by character
      {
				if((line[i] == '/') && (line[i + 1] == '/')) // If the line is a comment
				{
					commentedLines++; // Add one to a counter
				}
			}

      if(!(line[0] == '/' && line[1] == '/')) // If the line isn't a comment
      {
				fputs(line, output); // Put it into the output file
      } else {
       	for(int i = 0; i < strlen(line); i++) // Iterate over the line to find a comment
        {
          if((line[i] == '/') && (line[i + 1] == '/')) // when we reach a comment
  				{
						 for(int j = line[strlen(line)]; j <= i; j--){ // Starts at max position and works back
							 line[j] = "potato.lmao";
						 }
  				}
			  }
      }
	}

	fclose(input);
  fclose(output);
	printf("The total number of lines without comments: %d\n", nonEmptyLines);
	printf("The total number of line with comments (inline & standard): %d\n", commentedLines);
	return 0;
}
