#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define LINE_LENGTH 1000

int main(int argc, char const *argv[]) // Main method generated by atom.io
{

	FILE* input = fopen("math_functions.c", "r"); // Input file for read access only.
	char line[LINE_LENGTH];
	int nonEmptyLines = 0;
	int commentedLines = 0;

	FILE* output = fopen("math_functions.o", "w"); // Output file for write access // generates if it doesn't exist.
	while (fgets(line, LINE_LENGTH, input) != NULL) // To iterate over the whole file
	{
		if (!((line[0] == '\t')
			|| (line[0] == '\n')
			|| (line[0] == '\0'))) // If the line isn't completely empty, tabbed or nulled
		{
			nonEmptyLines++; // Add one to a counter
		}

		for (int i = 0; i < strlen(line); i++) // Iterate over the line by character
		{
			if ((line[i] == '/') && (line[i + 1] == '/')) // If the line is a comment
			{
				commentedLines++; // Add one to a counter
			}
		}

		for (int i = 0; i < strlen(line); i++) // Iterate over the line to find a comment
		{
			if (!(line[i] == '/') && (line[i + 1] == '/')) // If the line is a comment
			{
				fputs(line, output);
			}
		}
	}

	int totalNonEmptyLines = nonEmptyLines - commentedLines;

	fclose(input);
	fclose(output);
	printf("The total number of lines without comments: %d\n", totalNonEmptyLines);
	printf("The total number of line with comments (inline & standard): %d\n", commentedLines);

	return 0;
}